import React, { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { changeClerkPassword } from "../../../services/api/clerkService";
const ChangeClerkPasswordScreen = () =>
     { 
        const [form, setForm] = useState({ oldPassword: "", newPassword: "", confirm: "" });
         const [saving, setSaving] = useState(false);
          const submit = async () => { if (Object.values(form).some((value) => !value)) return Alert.alert("Validation", "Complete all password fields."); if (form.newPassword !== form.confirm) return Alert.alert("Validation", "New passwords do not match."); setSaving(true); try { await changeClerkPassword(form.oldPassword, form.newPassword); setForm({ oldPassword: "", newPassword: "", confirm: "" }); Alert.alert("Password changed", "Your password was changed successfully."); } catch (e) { Alert.alert("Password change failed", e.response?.data?.message || "Unable to change password."); } finally { setSaving(false); } }; return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Change Password</Text><View style={styles.card}>{[["Current Password", "oldPassword"], ["New Password", "newPassword"], ["Confirm Password", "confirm"]].map(([label, key]) => <View key={key} style={styles.field}><Text style={styles.label}>{label}</Text><TextInput secureTextEntry value={form[key]} onChangeText={(value) => setForm((old) => ({ ...old, [key]: value }))} style={styles.input} /></View>)}<Pressable disabled={saving} onPress={submit} style={[styles.button, saving && styles.disabled]}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={styles.buttonText}>Change Password</Text>}</Pressable></View></ScrollView></View>; };
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#D9DEE0" }, content: { padding: 20, paddingBottom: 40 }, title: { fontSize: 30, fontWeight: "700", color: "#19324D", marginBottom: 20 }, card: { backgroundColor: "#FCFAF5", borderWidth: 1, borderColor: "#E1DDD4", borderRadius: 18, padding: 20 }, field: { marginBottom: 14 }, label: { fontSize: 12, fontWeight: "600", color: "#293D53", marginBottom: 6 }, input: { height: 46, borderWidth: 1, borderColor: "#D8DEE4", borderRadius: 11, backgroundColor: "#FFF", paddingHorizontal: 12 }, button: { height: 46, borderRadius: 23, backgroundColor: "#122F4B", alignItems: "center", justifyContent: "center", marginTop: 4 }, disabled: { opacity: 0.6 }, buttonText: { color: "#FFF", fontWeight: "700" } });
export default ChangeClerkPasswordScreen;
