import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import AppScreen from "../../../components/layout/AppScreen";
import AppText from "../../../components/common/AppText";
import SettingsPageHeader from "../../../components/admin/settings/SettingsPageHeader";
import { getStaffProfile, updateStaffProfile } from "../../../services/api/authService";
export default function EditProfileScreen() { const [form, setForm] = useState({ fullName: "", email: "", mobile: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); useEffect(() => { getStaffProfile().then((data) => setForm({ fullName: data?.fullName ?? data?.name ?? "", email: data?.email ?? "", mobile: data?.mobile ?? data?.phone ?? "" })).catch(() => Alert.alert("Profile unavailable", "Unable to load profile.")).finally(() => setLoading(false)); }, []); const save = async () => { if (!form.fullName.trim() || !form.email.trim()) return Alert.alert("Validation", "Full name and email are required."); setSaving(true); try { await updateStaffProfile({ fullName: form.fullName.trim(), email: form.email.trim(), mobile: form.mobile.trim() }); Alert.alert("Profile updated", "Your profile was updated successfully."); } catch (error) { Alert.alert("Update failed", error.response?.data?.message || "Unable to update profile."); } finally { setSaving(false); } }; return <AppScreen><ScrollView><SettingsPageHeader title="Edit Profile"><View style={styles.card}>{loading ? <ActivityIndicator color="#102A43" /> : <><Field label="Full Name" value={form.fullName} onChangeText={(value) => setForm((old) => ({ ...old, fullName: value }))} /><Field label="Email" value={form.email} onChangeText={(value) => setForm((old) => ({ ...old, email: value }))} /><Field label="Mobile" value={form.mobile} onChangeText={(value) => setForm((old) => ({ ...old, mobile: value }))} /><AppText size="xs" color="textSecondary">Role and account identifiers are read-only.</AppText><Pressable disabled={saving} onPress={save} style={styles.button}><AppText style={styles.white}>{saving ? "Saving..." : "Save Changes"}</AppText></Pressable></>}</View></SettingsPageHeader></ScrollView></AppScreen>; }
const Field = ({ label, ...props }) => <View style={styles.field}><AppText size="sm" weight="semiBold">{label}</AppText><TextInput {...props} style={styles.input} /></View>;
const styles = StyleSheet.create({ card: { backgroundColor: "#FFFDF8", borderWidth: 1, borderColor: "#DED9CE", borderRadius: 18, padding: 16 }, field: { marginBottom: 14 }, input: { height: 46, borderWidth: 1, borderColor: "#DED9CE", borderRadius: 11, paddingHorizontal: 12, marginTop: 7 }, button: { height: 46, backgroundColor: "#102A43", borderRadius: 11, alignItems: "center", justifyContent: "center", marginTop: 14 }, white: { color: "#FFFDF8" } });
