import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import AppScreen from "../../../components/layout/AppScreen";
import AppText from "../../../components/common/AppText";
import SettingsPageHeader from "../../../components/admin/settings/SettingsPageHeader";
import { getStaffProfile, uploadStaffProfilePhoto } from "../../../services/api/authService";
export default function ProfileSettingsScreen({ navigation }) { const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); useEffect(() => { getStaffProfile().then(setProfile).catch((error) => Alert.alert("Profile unavailable", error.response?.data?.message || "Unable to load profile.")).finally(() => setLoading(false)); }, []); const choosePhoto = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.8 }); if (result.canceled || !result.assets?.[0]) return; setUploading(true); try { await uploadStaffProfilePhoto(result.assets[0]); setProfile(await getStaffProfile()); Alert.alert("Photo updated", "Profile photo updated successfully."); } catch (error) { Alert.alert("Photo upload failed", error.response?.data?.message || "Unable to upload profile photo."); } finally { setUploading(false); } }; const fields = [["Full Name", profile?.fullName ?? profile?.name], ["Email", profile?.email], ["Phone", profile?.mobile ?? profile?.phone], ["Role", profile?.role], ["User ID", profile?.userId ?? profile?.appUserId], ["Department", profile?.department], ["Office", profile?.office], ["Joining Date", profile?.joiningDate]]; return <AppScreen><ScrollView><SettingsPageHeader title="Profile"><View style={styles.card}>{loading ? <ActivityIndicator color="#102A43" /> : <><Pressable disabled={uploading} onPress={choosePhoto} style={styles.avatar}><AppText size="xl" weight="bold">{uploading ? "…" : String(profile?.fullName ?? profile?.name ?? "U").charAt(0).toUpperCase()}</AppText></Pressable><AppText size="xs" color="textSecondary" style={styles.photoHint}>Tap the avatar to change photo</AppText>{fields.filter(([, value]) => value != null && value !== "").map(([label, value]) => <View key={label} style={styles.row}><AppText size="xs" color="textSecondary">{label}</AppText><AppText weight="semiBold">{String(value)}</AppText></View>)}<Pressable onPress={() => navigation.navigate("AdminEditProfile")} style={styles.button}><AppText style={styles.white}>Edit Profile</AppText></Pressable></>}</View></SettingsPageHeader></ScrollView></AppScreen>; }
const styles = StyleSheet.create({ card: { backgroundColor: "#FFFDF8", borderWidth: 1, borderColor: "#DED9CE", borderRadius: 18, padding: 16 }, avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: "#F7EAC5", alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 6 }, photoHint: { textAlign: "center", marginBottom: 8 }, row: { minHeight: 52, justifyContent: "center", borderBottomWidth: 1, borderBottomColor: "#DED9CE" }, button: { height: 44, borderRadius: 11, backgroundColor: "#102A43", alignItems: "center", justifyContent: "center", marginTop: 16 }, white: { color: "#FFFDF8" } });
