import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import ClientStatCard from "../../../components/clients/dashboard/ClientStatCard";
import CaseStatusChart from "../../../components/clients/dashboard/CaseStatusChart";
import InvoiceStatusChart from "../../../components/clients/dashboard/InvoiceStatusChart";
import LatestCaseSnapshot from "../../../components/clients/dashboard/LatestCaseSnapshot";

const ClientDashboardScreen = () => { const stats = [{ label: "TOTAL CASES", value: 1, accent: "blue" }, { label: "ACTIVE CASES", value: 1, accent: "yellow" }, { label: "CLOSED CASES", value: 0, accent: "red" }, { label: "UPCOMING HEARINGS", value: 0, accent: "green" }, { label: "PENDING INVOICES", value: 0, accent: "yellow" }, { label: "PAID INVOICES", value: 0, accent: "green" }, { label: "RECENT NOTIFICATIONS", value: 0, accent: "blue" }, { label: "OUTSTANDING BALANCE", value: 0, prefix: "₹ ", accent: "red" }]; const caseStatusData = [{ label: "New", value: 1 }, { label: "Assigned", value: 0 }, { label: "In Progress", value: 0 }, { label: "Hearing Scheduled", value: 0 }, { label: "Closed", value: 0 }]; const invoiceStatusData = [{ label: "Pending Invoices", value: 0, color: "#D9AF32" }, { label: "Paid Invoices", value: 0, color: "#20A34A" }, { label: "Outstanding Balance", value: 0, color: "#061C2B" }]; const latestCase = { caseNumber: "CIV-2026-003", title: "Kiran Babu vs. ABC Developers", lawyer: "Sowmya Advocate", status: "New", nextHearing: "10 Aug 2026", payment: "No pending payment" }; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.heading}><Text style={styles.title}>Dashboard</Text><Text style={styles.subtitle}>Welcome back! Here is an overview of your legal matters.</Text></View><View style={styles.stats}>{stats.map(item => <ClientStatCard key={item.label} {...item} />)}</View><View style={styles.charts}><CaseStatusChart data={caseStatusData} /><InvoiceStatusChart data={invoiceStatusData} /></View><LatestCaseSnapshot caseData={latestCase} /></ScrollView> };
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#D9DEE0" }, content: { padding: 20, paddingBottom: 110, gap: 18 }, heading: { marginTop: 25, marginBottom: 2 }, title: { fontSize: 34, lineHeight: 41, fontWeight: "700", color: "#19324D" }, subtitle: { marginTop: 6, fontSize: 15, lineHeight: 21, color: "#60758E" }, stats: { flexDirection: "row", flexWrap: "wrap", gap: 14 }, charts: { flexDirection: "row", flexWrap: "wrap", gap: 16 } }); export default ClientDashboardScreen;
